variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: Docker-service-connection
    imageRepository: smrutiranjan7674
    containerRegistry: devops-azure-test
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: 'latest'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'

